# Generated by Django 3.2.19 on 2023-05-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='preview',
        ),
    ]
